In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/googlenewsvectorsnegative300/GoogleNews-vectors-negative300.bin.gz
/kaggle/input/googlenewsvectorsnegative300/GoogleNews-vectors-negative300.bin
/kaggle/input/youtube/GBvideos.csv
/kaggle/input/youtube/UScomments.csv
/kaggle/input/youtube/GB_category_id.json
/kaggle/input/youtube/US_category_id.json
/kaggle/input/youtube/GBcomments.csv
/kaggle/input/youtube/USvideos.csv


In [3]:
# import googleapiclient.discovery
# import pandas as pd

# api_service_name = "youtube"
# api_version = "v3"
# DEVELOPER_KEY = "AIzaSyAS1qvkRUNvz1UOqBjUaVDRT21gPyuqF1M"

# youtube = googleapiclient.discovery.build(
#     api_service_name, api_version, developerKey=DEVELOPER_KEY)

# request = youtube.commentThreads().list(
#     part="snippet",
#     videoId="KPLWWIOCOOQ",
#     maxResults=999
# )
# response = request.execute()

# comments = []

# for item in response['items']:
#     comment = item['snippet']['topLevelComment']['snippet']
#     comments.append([
# #         comment['authorDisplayName'],
# #         comment['publishedAt'],
# #         comment['updatedAt'],
# #         comment['likeCount'],
#         comment['textDisplay']
#     ])
# # 'author', 'published_at', 'updated_at',
# df = pd.DataFrame(comments, columns=['Comment'])

# df.shape

In [4]:
# pd.set_option('display.max_columns',None)

US_comments = pd.read_csv('../input/youtube/UScomments.csv', on_bad_lines='skip')

GB_comments = pd.read_csv('/kaggle/input/youtube/GBcomments.csv', on_bad_lines='skip')

US_comments.head()

GB_comments.head()

df1=US_comments['comment_text']
df2=GB_comments['comment_text']

print(df1.shape)
print(df2.shape)

df1=df1[:25000]
df2=df2[:25000]

df = pd.DataFrame(pd.concat([df1, df2]))

# df=pd.DataFrame(df1)

print(df.shape)

df.head()

/tmp/ipykernel_26/3420677335.py:3: DtypeWarning: Columns (2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  US_comments = pd.read_csv('../input/youtube/UScomments.csv', on_bad_lines='skip')


(691400,)
(718452,)
(50000, 1)


comment_text
0                  Logan Paul it's yo big day ‼️‼️‼️
1  I've been following you from the start of your...
2                 Say hi to Kong and maverick for me
3                                MY FAN . attendance
4                                         trending 😉

In [5]:
df.rename(columns = {'comment_text':'Comment'}, inplace = True)

In [6]:
#Libraries 
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline
import os

# Import functions for data preprocessing & data preparation
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample
from sklearn.feature_extraction.text import CountVectorizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import string
from string import punctuation
import nltk
import emoji
import re

!pip install twython

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


  Obtaining dependency information for twython from https://files.pythonhosted.org/packages/db/08/9921df4cb5829858dbd580ebd8a5a4b9e75a0b8295bc1e98963a983a0621/twython-3.9.1-py3-none-any.whl.metadata


In [7]:
# data1=df.sort_values(by = 'like_count',ascending=False)
# data1.head()
data1=df
data1.head()


print(data1.shape)
data1.head()


(50000, 1)


Comment
0                  Logan Paul it's yo big day ‼️‼️‼️
1  I've been following you from the start of your...
2                 Say hi to Kong and maverick for me
3                                MY FAN . attendance
4                                         trending 😉

In [8]:
nltk.download('vader_lexicon')
sentiments = SentimentIntensityAnalyzer()
data1["Positive"] = [sentiments.polarity_scores(str(i))["pos"] for i in data1["Comment"]]
data1["Negative"] = [sentiments.polarity_scores(str(i))["neg"] for i in data1["Comment"]]
data1["Neutral"] = [sentiments.polarity_scores(str(i))["neu"] for i in data1["Comment"]]
data1['Compound'] = [sentiments.polarity_scores(str(i))["compound"] for i in data1["Comment"]]

score = data1["Compound"].values
sentiment = []
for i in score:
    if i >= 0.05 :
        sentiment.append('Positive')
    elif i <= -0.05 :
        sentiment.append('Negative')
    else:
        sentiment.append('Neutral')
data1["Sentiment"] = sentiment
data1.head()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /usr/share/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


Comment  Positive  Negative  \
0                  Logan Paul it's yo big day ‼️‼️‼️     0.000       0.0   
1  I've been following you from the start of your...     0.000       0.0   
2                 Say hi to Kong and maverick for me     0.000       0.0   
3                                MY FAN . attendance     0.603       0.0   
4                                         trending 😉     0.000       0.0   

   Neutral  Compound Sentiment  
0    1.000    0.0000   Neutral  
1    1.000    0.0000   Neutral  
2    1.000    0.0000   Neutral  
3    0.397    0.4648  Positive  
4    1.000    0.0000   Neutral

In [9]:
data2=data1.drop(['Positive','Negative','Neutral','Compound'],axis=1)
data2.head()

Comment Sentiment
0                  Logan Paul it's yo big day ‼️‼️‼️   Neutral
1  I've been following you from the start of your...   Neutral
2                 Say hi to Kong and maverick for me   Neutral
3                                MY FAN . attendance  Positive
4                                         trending 😉   Neutral

In [10]:
stop_words = stopwords.words('english')

In [11]:
def text_processing(text):   
    # convert text into lowercase
    text = text.lower()

    # remove new line characters in text
    text = re.sub(r'\n',' ', text)
    
    # remove punctuations from text
    text = re.sub('[%s]' % re.escape(punctuation), "", text)
    
    # remove references and hashtags from text
    text = re.sub("^a-zA-Z0-9$,.", "", text)
    
    # remove multiple spaces from text
    text = re.sub(r'\s+', ' ', text, flags=re.I)
    
    # remove special characters from text
    text = re.sub(r'\W', ' ', text)
    
    emoji.demojize(text)

    text = ' '.join([word for word in word_tokenize(text) if word not in stop_words])

    return text

In [12]:
# nltk.download('omw-1.4')
data_copy = data2.copy()
data_copy.Comment = data_copy.Comment.apply(lambda text: text_processing(str(text)))

data_copy.head()

Comment Sentiment
0                            logan paul yo big day   Neutral
1  ive following start vine channel seen 365 vlogs   Neutral
2                             say hi kong maverick   Neutral
3                                   fan attendance  Positive
4                                         trending   Neutral

In [13]:
le = LabelEncoder()
data_copy['Sentiment'] = le.fit_transform(data_copy['Sentiment'])
data_copy.head()

Comment  Sentiment
0                            logan paul yo big day          1
1  ive following start vine channel seen 365 vlogs          1
2                             say hi kong maverick          1
3                                   fan attendance          2
4                                         trending          1

In [14]:
processed_data = {
    'Sentence':data_copy.Comment,
    'Sentiment':data_copy['Sentiment'],
#     'Likes':data_copy['like_count']
}

processed_data = pd.DataFrame(processed_data)
processed_data.head(20)



Sentence  Sentiment
0                               logan paul yo big day          1
1     ive following start vine channel seen 365 vlogs          1
2                                say hi kong maverick          1
3                                      fan attendance          2
4                                            trending          1
5                                 1 trending ayyeeeee          1
6                                          end though          1
7                                          1 trending          1
8                         happy one year vlogaversary          2
9   shit brother may single handedly ruined youtub...          0
10                                    mini logan paul          1
11  dear logan really wan na get merch dont money ...          2
12  honestly evan annoying like funny watching try...          0
13                           casey still better logan          2
14                      aw geez rick guy face youtube          1
15                                  happy cause movie          2
16  ayyyyoooo logang hard vlog watch logan dare de...          2
17           bro didnt u give merch johannes ur boy 2          1
18  fun watching grow im 42 days straight cant see...          2
19                    made lot people hate youtube gj          1

In [15]:
processed_data['Sentiment'].value_counts()

Sentiment
2    23036
1    17134
0     9830
Name: count, dtype: int64

In [16]:
df_neutral = processed_data[(processed_data['Sentiment']==1)] 
df_negative = processed_data[(processed_data['Sentiment']==0)]
df_positive = processed_data[(processed_data['Sentiment']==2)]

# # upsample minority classes
# df_negative_upsampled = resample(df_negative, 
#                                  replace=True,    
#                                  n_samples= 300, 
#                                  random_state=42)  

# df_neutral_upsampled = resample(df_neutral, 
#                                  replace=True,    
#                                  n_samples= 300, 
#                                  random_state=42)  

# df_positive_upsampled = resample(df_positive, 
#                                  replace=False,    
#                                  n_samples= 13716, 
#                                  random_state=42)  

# df_neutral_upsampled = resample(df_neutral, 
#                                  replace=False,    
#                                  n_samples= 13716, 
#                                  random_state=42) 


# Concatenate the upsampled dataframes with the neutral dataframe
# final_data = pd.concat([df_negative,df_neutral_upsampled,df_positive_upsampled])

final_data=processed_data

In [17]:
final_data['Sentiment'].value_counts()

Sentiment
2    23036
1    17134
0     9830
Name: count, dtype: int64

In [18]:
corpus = []
for sentence in final_data['Sentence']:
    corpus.append(sentence)
corpus[0:5]

['logan paul yo big day',
 'ive following start vine channel seen 365 vlogs',
 'say hi kong maverick',
 'fan attendance',
 'trending']

In [19]:
# from sklearn.feature_extraction.text import CountVectorizer
# cv = CountVectorizer(max_features=400,binary=True,ngram_range=(1,5))
# X = cv.fit_transform(corpus).toarray()
# y = final_data.iloc[:, -1].values
# # X.shape__sizeof__

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer(max_features=6000,binary=True,ngram_range=(1,6))
X = tf.fit_transform(corpus).toarray()
y = final_data.iloc[:, -1].values
# print(X)
# X.shape

In [31]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

forest=RandomForestClassifier()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
# classifier = GaussianNB()
# classifier.fit(X_train, y_train)
forest.fit(X_train,y_train)


RandomForestClassifier()

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
# y_pred = classifier.predict(X_test)
# y_pre = classifier.predict(X_train)
y_preds=forest.predict(X_test)
# cm = confusion_matrix(y_test, y_pred)
cm1 = confusion_matrix(y_test, y_preds)
# print(cm)
print(cm1)


[[2176  279  567]
 [  85 4813  248]
 [ 113  269 6450]]


In [33]:
# nb_score = accuracy_score(y_test, y_pred)
# nb_score = accuracy_score(y_train, y_train)
nb_score1 = accuracy_score(y_test, y_preds)
# print('accuracy',nb_score)
print('accuracy',nb_score1)
print(y_preds.shape)
y_preds.shape
# print(y_pre)

accuracy 0.8959333333333334
(15000,)


(15000,)

In [29]:
# import pickle 
# pickle.dump(forest,open('forest.pkl','wb'))